force-app/main/default/objects/Cruise_Room__c/Cruise_Room__c.object-meta.xml
<CustomObject>
    <label>Cruise Room</label>
    <nameField>
        <displayFormat>RoomID-{000000000}</displayFormat>
        <label>Room ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cruise Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cruise_Room__c/fields/Passenger_Price__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Price__c</fullName>
    <label>Passenger Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cruise_Room__c/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room Type</label>
    <referenceTo>Room_Type__c</referenceTo>
    <relationshipLabel>Cruise Rooms</relationshipLabel>
    <relationshipName>Cruise_Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room_Type__c/Room_Type__c.object-meta.xml
<CustomObject>
    <label>Room Type</label>
    <nameField>
        <label>Room Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Room Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LwcBulkRoomControllerF1417.cls
public with sharing class LwcBulkRoomControllerF1417 {

    @AuraEnabled
    public static void createBulkRoom(Integer HowMuch, id cruiseship, id Roomtypes,Decimal Price, Integer Capacitys){
        
       
    	List<Cruise_Room__c> BulkRoom = New List<Cruise_Room__c>();
        Integer x=1;
        for(x=1;x<=Howmuch;x++){
            Cruise_Room__c newrecord = New Cruise_Room__c();
            newrecord.Cruise_Ship__c=cruiseship;                                      
            newrecord.Room_Type__c=Roomtypes;                             
          
            newrecord.Passenger_Price__c=Price;
            newrecord.Capacity__c=Capacitys;
            
            BulkRoom.add(newrecord);
        }
       insert BulkRoom;

    }
}