force-app/main/default/objects/Room_Type__c/Room_Type__c.object-meta.xml
<CustomObject>
    <label>Room Type</label>
    <nameField>
        <label>Room Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Room Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room_Type__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room_Type__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jakuzi</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Klima</fullName>
            </value>
            <value>
                <fullName>Minibar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RoomTypeCreate.cls
public with sharing class RoomTypeCreate {
	/* Integer HowMuch;
    String	Name;
    Decimal Price;
    String Feature;
    String Classes; */
    
    @AuraEnabled
    public static void createRoomType(Integer HowMuch, String Name,Decimal Price, String Feature, String Classes){
        
    	List<Room_Type__c> RoomType = New List<Room_Type__c>();
        Integer x=1;
        for(x=1;x<=Howmuch;x++){
            Room_Type__c newrecord = New Room_Type__c();
            newrecord.Name=Name+' '+x;
          	newrecord.Price__c=Price;
            newrecord.Feature__c=Feature;
            newrecord.Class__c=Classes;
            RoomType.add(newrecord);
        }
        insert RoomType;
    }
}